Programmes crud api
Project-Kampong/kampong-backend pull request #215
Opened 2020-10-14 04:21 UTC by abdurrahmanfaqihiskandar

2020-10-25 02:39 UTC, don-tay requested changes
The database schema looks good. For the endpoints, we can be more lenient in our data input requirements.

Lets review the organisations and programmes creation flow with FE after this PR, so that we can work on the permissions and `is_verirfied` flag

2020-10-25 02:39 UTC, don-tay commented on src/controllers/programmes.ts
> +    }
```suggestion
    // check if programme exists
await  db.one('SELECT * FROM programmes WHERE programme_id = $1', req.params.id);
```

2020-10-25 02:39 UTC, don-tay commented on src/controllers/programmes.ts
> +    }
Must add check to allow for organisation owner

2020-10-25 02:39 UTC, don-tay commented on src/routes/api/organisation-routes.ts
> +    check('handphone', INVALID_PHONE_NUMBER_MSG).trim().notEmpty(),
Let's make handphone optional for now

2020-10-25 06:24 UTC, don-tay commented on src/database/schema.sql
> +	TYPE VARCHAR,
```suggestion
	type VARCHAR,
```

2020-10-25 06:29 UTC, don-tay commented on src/database/schema.sql
>  CREATE TABLE Organisations (
For `Organisations`, additionally add 
`locations VARCHAR`, optional field
`story TEXT` optional field

2020-10-25 06:29 UTC, don-tay commented on src/database/schema.sql
>  CREATE TABLE Organisations (
Do add these columns on the create and update endpoints

2020-11-01 12:56 UTC, don-tay approved these changes
Small updates to the schema (and change the endpoint naming to fit this as well) and it LGTM

2020-11-01 18:05 UTC, Kalsyc approved these changes
LGTM 👍🏻

2020-11-02 01:10 UTC, merged